sudo: true
language: ruby
rvm:
  - 2.5.1

before_install:
  - sudo apt update
  - sudo apt-get install build-essential libxml2-dev libfftw3-dev gettext libgtk2.0-dev python-dev liblcms1-dev liboil-dev libmagickwand-dev libopenexr-dev libcfitsio3-dev	gobject-introspection
  - sudo apt-get install automake libtool swig gtk-doc-tools
  - git clone https://github.com/jcupitt/libvips.git
  - cd libvips
  - ./autogen.sh
  - make
  - sudo make install
  - gem install bundler

install:
  - bundle install

script:
  - bundle exec rake test
